### ISSUE TITLE
Update app.js - bodyParser no longer included as part of Express

### ISSUE THREAD

**Issue by crashspringfield** [DHTMLX/node-scheduler-demo#3]
Body Parser is no longer part of the Express package. 

Add: 

      var bodyParser = require('body-parser');
to the list of dependencies and:

      app.use(bodyParser.json());
after initiating the app.

**Comment by AlexKlimenkov** [comment]
updated in https://github.com/DHTMLX/node-scheduler-demo/commit/c0e68bef91e9917e2f06acdfd512b3836942a7a4
